server:
  port: 8088
  servlet:
    context-path: /metoo
spring:
  application:
    name: metoo-web

dubbo:
  scan:
    base-packages: com.metoo.api.service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    timeout: 6000
    check: false
  metadata-report:
    address: zookeeper://127.0.0.1:2181


