server:
  port: 8088

rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: loongyametoo        #jwt秘钥
  expiration: 31104000      #1年 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: loongyametooyan      #md5加密混淆key
  ignore-url: /register,/modifyPassword,/wxorder/notify,/app,/ps #忽略列表




spring:
  application:
    name: metoo-web
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 10

queue-name: publish.queue
topic-name: publish.topic

dubbo:
  scan:
    base-packages: com.metoo.web
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    timeout: 6000
    check: false
  metadata-report:
    address: zookeeper://127.0.0.1:2181


