server:
  port: 8088

rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /user/register,/user/check,/film/getIndex,/film/getConditionList,/film/getFilms,/film/films,/cinema/getCinemas,/cinema/getCondition,/cinema/getFields,/cinema/getFieldInfo #忽略列表




spring:
  application:
    name: metoo-web

dubbo:
  scan:
    base-packages: com.metoo.web
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    timeout: 6000
    check: false
  metadata-report:
    address: zookeeper://127.0.0.1:2181


