server:
  port: 8088
spring:
  application:
    name: metoo-web

dubbo:
  scan:
    base-packages: com.metoo.web
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    timeout: 6000
    check: false
  metadata-report:
    address: zookeeper://127.0.0.1:2181


