server:
  port: 8089

rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: loongyametoo        #jwt秘钥
  expiration: 31104000      #1年 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: loongyametooyan      #md5加密混淆key
  ignore-url: /register #忽略列表

wechat:
  appid: wxbb69a9cc679fba31
  secret: e23f2f592fc80768b1a6bacbb97a0856
  grant-type: authorization_code
  login-url: https://api.weixin.qq.com/sns/jscode2session

spring:
  application:
    name: metoo-wechat-web
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 10

queue-name: publish.queue
topic-name: publish.topic

dubbo:
  scan:
    base-packages: com.metoo.wechat
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    timeout: 6000
    check: false
  metadata-report:
    address: zookeeper://127.0.0.1:2181


