server:
  port: 8084
spring:
  application:
    name: metoo-im
  datasource:
    druid:
      username: root
      password: '@Jy940327'
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.111.98.218:3306/metoo?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
      initialSize: 10 #初始化连接池大小
      minIdle: 10 #连接池中保留最小连接数
      maxActive: 60 # 连接池中保留最大连接数
      max-wait: 60 # 配置获取连接等待超时的时间
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      test-while-idle: true # 空闲的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效
      validation-query: select 'x' # 检测sql
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，开启这个配置会降低性能 线上不开启
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，开启这个配置会降低性能 线上不开启
      pool-prepared-statements: true # 开启PSCache 会消耗一定的内存 但能提高性能
      max-open-prepared-statements: 20 # 每个connection PSCache 缓存语句的数量
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


mybatis-plus:
  mapper-locations: classpath:com/metoo/im/**/dao/mapper/mapping/*.xml
  configLocation: classpath:/mybatis-config.xml
  global-config:
    banner: true # 是否控制台 print mybatis-plus 的 LOGO


dubbo:
  scan:
    base-packages: com.metoo.api.service
  protocol:
    name: dubbo
    port: 20880
  consumer:
    timeout: 6000
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  metadata-report:
    address: zookeeper://127.0.0.1:2181

